# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8MdSKMgJXQrcmp2X2lSZAYXytQee2vQ
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('householdtask3.csv')

df

# Creating a bar chart to visualize total households ('tot_hhs') by year
plt.figure(figsize=(12, 6))
plt.bar(df['year'], df['tot_hhs'], color='skyblue', label='Total Households')
plt.xlabel('Year')
plt.ylabel('Total Households')
plt.title('Total Households by Year')
plt.legend()
plt.show()

# Creating a line chart to visualize household ownership ('own') and average income ('income') over the years
plt.figure(figsize=(12, 6))
plt.plot(df['year'], df['own'], marker='o', linestyle='-', color='green', label='Household Ownership')
plt.plot(df['year'], df['income'], marker='s', linestyle='-', color='blue', label='Average Income')
plt.xlabel('Year')
plt.ylabel('Values')
plt.title('Household Ownership and Average Income by Year')
plt.legend()
plt.show()

